export const STORAGE_KEYS = {
  onboardingDone: 'nivesha:onboarding_done',
  termsAccepted: 'nivesha:terms_accepted_v1',
  language: 'nivesha:pref:language',
  bestScore: 'nivesha:quiz:best_score',
  entitlements: 'nivesha:entitlements',
  profile: 'nivesha:profile',
  paperTrading: 'nivesha:paper_trading',
  journal: 'nivesha:journal',
  journalInsightCache: 'nivesha:journal:insight_cache',
  journalDismissedTradeKeys: 'nivesha:journal:dismissed_trade_keys',
  coachIntroSeen: 'nivesha:coach_intro_seen_v4',
  coachFabPosition: 'nivesha:coach_fab_position',
  themeMode: 'nivesha:pref:theme_mode',
  notificationsEnabled: 'nivesha:pref:notifications_enabled',
};
